# Generated by Django 2.1.7 on 2021-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210203_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Details',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
