# Generated by Django 2.1 on 2021-03-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Details',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
