# Generated by Django 2.1 on 2021-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210320_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
