# Generated by Django 2.1.7 on 2021-02-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210201_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
