# Generated by Django 2.1 on 2021-05-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=120, null=True)),
                ('Cc', models.CharField(max_length=120, null=True)),
                ('Details', models.CharField(max_length=120, null=True)),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
