# Generated by Django 2.1 on 2021-05-07 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20210507_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
