# Generated by Django 2.1 on 2021-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20210507_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Cc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Details',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
